site_name: Opsec C
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra_css:
  - stylesheets/styles.css
extra_javascript:
  - scripts/theme_changer.js
validation:
  omitted_files: ignore
  absolute_links: ignore
  unrecognized_links: ignore
  not_found: ignore
theme:
  name: material
  font:
    text: Courier New
  palette:
    scheme: custom
    primary: custom
    accent: custom
nav:
    - Home: index.md
    - Opsecs:
      - Opsec C: opsecs/opsecC.md
      - Opsec R: opsecs/opsecR.md
    - General Rules: opsecs/tips.md
    - Role List: opsecs/rolelist.md
    - Roles:
      - Netsec:
        - Netsec: rolelist/netsec/netsec.md
        - Netsec Special:
          - Operation Leader: rolelist/netsec/NetsecSpecial/OperationLeader.md
          - Former Agent Leader: rolelist/netsec/NetsecSpecial/FormerAgentLeader.md
          - Hack God: rolelist/netsec/NetsecSpecial/HackGod.md
          - Infamous Cybercriminal: rolelist/netsec/NetsecSpecial/InfamousCybercriminal.md
          - Old Friend: rolelist/netsec/NetsecSpecial/OldFriend.md
        - Netsec Field Operations:
          - Enforcer: rolelist/netsec/NetsecFieldOps/Enforcer.md
          - CCTV Specialist: rolelist/netsec/NetsecFieldOps/CCTVSpecialist.md
          - Rookie Hacker: rolelist/netsec/NetsecFieldOps/RookieHacker.md
          - Improvised Hacker: rolelist/netsec/NetsecFieldOps/ImprovisedHacker.md
          - Nightclub Guard: rolelist/netsec/NetsecFieldOps/NightclubGuard.md
          - Hardware Hacker: rolelist/netsec/NetsecFieldOps/HardwareHacker.md
          - Entertainer: rolelist/netsec/NetsecFieldOps/Entertainer.md
          - Getaway Driver: rolelist/netsec/NetsecFieldOps/GetawayDriver.md
          - Arms Dealer: rolelist/netsec/NetsecFieldOps/ArmsDealer.md
        - Netsec Investigative:
          - Analyst: rolelist/netsec/NetsecInvest/Analyst.md
          - Social Engineer: rolelist/netsec/NetsecInvest/SocialEngineer.md
          - Computer Technician: rolelist/netsec/NetsecInvest/ComputerTechnician.md
          - Inside Man (Detective): rolelist/netsec/NetsecInvest/InsideManDetective.md
          - Dark Web Contact: rolelist/netsec/NetsecInvest/DarkWebContact.md
          - Natural Linguist: rolelist/netsec/NetsecInvest/NaturalLinguist.md
          - Computer Vision Engineer: rolelist/netsec/NetsecInvest/ComputerVisionEngineer.md
          - Technical Project Manager: rolelist/netsec/NetsecInvest/TechnicalProjectManager.md
          - Search Engine Optimizer: rolelist/netsec/NetsecInvest/SearchEngineOptimizer.md
          - AI Generalist: rolelist/netsec/NetsecInvest/AIGeneralist.md
        - Netsec Offensive:
          - Network Specialist: rolelist/netsec/NetsecOffensive/NetworkSpecialist.md
          - Blackhat: rolelist/netsec/NetsecOffensive/Blackhat.md
          - Prodigy: rolelist/netsec/NetsecOffensive/Prodigy.md
          - Laptop Specialist: rolelist/netsec/NetsecOffensive/LaptopSpecialist.md
          - Server Specialist: rolelist/netsec/NetsecOffensive/ServerSpecialist.md
          - Steadfast Student: rolelist/netsec/NetsecOffensive/SteadfastStudent.md
          - Network Architect: rolelist/netsec/NetsecOffensive/NetworkArchitect.md
          - Inside Man (Software Engineer): rolelist/netsec/NetsecOffensive/InsideManSoftwareEngineer.md
          - Graph Theorist: rolelist/netsec/NetsecOffensive/GraphTheorist.md
          - Reverse Cryptographer: rolelist/netsec/NetsecOffensive/ReverseCryptographer.md
        - Netsec Utility:
          - Inside Man (Assistant): rolelist/netsec/NetsecUtility/InsideManAssistant.md
          - Hacking Instructor: rolelist/netsec/NetsecUtility/HackingInstructor.md
          - Spearphisher: rolelist/netsec/NetsecUtility/Spearphisher.md
          - Loan Shark: rolelist/netsec/NetsecUtility/LoanShark.md
          - Propagandist: rolelist/netsec/NetsecUtility/Propagandist.md
          - Maintenance Man: rolelist/netsec/NetsecUtility/MaintenanceMan.md
          - Malware Programmer: rolelist/netsec/NetsecUtility/MalwareProgrammer.md
          - Sympathetic Reporter: rolelist/netsec/NetsecUtility/SympatheticReporter.md
          - Drug Dealer: rolelist/netsec/NetsecUtility/DrugDealer.md
          - Criminal Coroner: rolelist/netsec/NetsecUtility/CriminalCoroner.md
        - Netsec Social:
          - Disgraced Loyalist: rolelist/netsec/NetsecSocial/DisgracedLoyalist.md
          - Double Agent: rolelist/netsec/NetsecSocial/DoubleAgent.md
          - Hacking Advocate: rolelist/netsec/NetsecSocial/HackingAdvocate.md
          - Technical Recruiter: rolelist/netsec/NetsecSocial/TechnicalRecruiter.md
          - Silenced Investigator: rolelist/netsec/NetsecSocial/SilencedInvestigator.md
          - Rookie Assassin: rolelist/netsec/NetsecSocial/RookieAssassin.md
          - Social Media Manager: rolelist/netsec/NetsecSocial/SocialMediaManager.md
          - NFT Scammer: rolelist/netsec/NetsecSocial/NFTScammer.md
          - Vibe Coder: rolelist/netsec/NetsecSocial/VibeCoder.md
      - Neutral:
        - Neutral:
          - Neutral: rolelist/neutral/neutral.md
          - Neutral Killing: rolelist/neutral/nk.md
        - Neutral Special:
          - Neutral Leader: rolelist/neutral/NeutralSpecial/NeutralLeader.md
          - Gambling Leader: rolelist/neutral/NeutralSpecial/GamblingLeader.md
          - Cheeseburger Technician: rolelist/neutral/NeutralSpecial/CheeseburgerTechnician.md
          - Sociopath: rolelist/neutral/NeutralSpecial/Sociopath.md
          - Resentful Criminal: rolelist/neutral/NeutralSpecial/ResentfulCriminal.md
          - The Employer: rolelist/neutral/NeutralSpecial/TheEmployer.md
        - Neutral Field Operations:
          - Loose Cannon: rolelist/neutral/NeutralFieldOps/LooseCannon.md
          - Bounty Hunter: rolelist/neutral/NeutralFieldOps/BountyHunter.md
          - Criminal Freelancer: rolelist/neutral/NeutralFieldOps/CriminalFreelancer.md
          - Insane Officer: rolelist/neutral/NeutralFieldOps/InsaneOfficer.md
          - Former Bodyguard: rolelist/neutral/NeutralFieldOps/FormerBodyguard.md
          - Contracted Headhunter: rolelist/neutral/NeutralFieldOps/ContractedHeadhunter.md
        - Neutral Investigative:
          - Journalist: rolelist/neutral/NeutralInvest/Journalist.md
          - Double Crosser: rolelist/neutral/NeutralInvest/DoubleCrosser.md
          - Shamed Journalist: rolelist/neutral/NeutralInvest/ShamedJournalist.md
          - Amateur Investigator: rolelist/neutral/NeutralInvest/AmateurInvestigator.md
          - Private Investigator: rolelist/neutral/NeutralInvest/PrivateInvestigator.md
          - Repressed Refugee: rolelist/neutral/NeutralInvest/RepressedRefugee.md
          - Vengeful Assassin: rolelist/neutral/NeutralInvest/VengefulAssassin.md
        - Neutral Offensive:
          - Script Kiddie: rolelist/neutral/NeutralOffensive/ScriptKiddie.md
          - Panicked Blabbermouth: rolelist/neutral/NeutralOffensive/PanickedBlabbermouth.md
          - Rival Hacker: rolelist/neutral/NeutralOffensive/RivalHacker.md
          - Hacknet Hacker: rolelist/neutral/NeutralOffensive/HacknetHacker.md
          - Connection Specialist: rolelist/neutral/NeutralOffensive/ConnectionSpecialist.md
          - Discord Manager: rolelist/neutral/NeutralOffensive/DiscordManager.md
        - Neutral Utility:
          - W.P.P. Member: rolelist/neutral/NeutralUtility/WPPMember.md
          - Insane Drug Dealer: rolelist/neutral/NeutralUtility/InsaneDrugDealer.md
          - Retired Hacker: rolelist/neutral/NeutralUtility/RetiredHacker.md
          - Disconnected Paragon Operative: rolelist/neutral/NeutralUtility/DisconnectedParagonOperative.md
          - Abandoned Agent: rolelist/neutral/NeutralUtility/AbandonedAgent.md
          - Political Campaigner: rolelist/neutral/NeutralUtility/PoliticalCampaigner.md
        - Neutral Social:
          - Corrupt Detective: rolelist/neutral/NeutralSocial/CorruptDetective.md
          - Waxmart Manager: rolelist/neutral/NeutralSocial/WaxmartManager.md
          - Corrupt Lawyer: rolelist/neutral/NeutralSocial/CorruptLawyer.md
          - Reminiscing Amnesiac: rolelist/neutral/NeutralSocial/ReminiscingAmnesiac.md
          - King of Trolls: rolelist/neutral/NeutralSocial/KingOfTrolls.md
          - Wildcard: rolelist/neutral/NeutralSocial/Wildcard.md
          - Drunken Agent: rolelist/neutral/NeutralSocial/DrunkenAgent.md
        - Neutral Killing:
          - Sociopath Leader: rolelist/neutral/NeutralKilling/SociopathLeader.md
          - Rogue Mastermind: rolelist/neutral/NeutralKilling/RogueMastermind.md
          - F/A-18 Super Hornet Pilot: rolelist/neutral/NeutralKilling/FA18SuperHornetPilot.md
          - Psychopath: rolelist/neutral/NeutralKilling/Psychopath.md
          - Bombardier: rolelist/neutral/NeutralKilling/Bombadier.md
          - Rogue Assassin: rolelist/neutral/NeutralKilling/RogueAssassin.md
          - Underground Ring Fighter: rolelist/neutral/NeutralKilling/UndergroundRingFighter.md
          - Italian Mafia: rolelist/neutral/NeutralKilling/ItalianMafia.md
      - Agent:
        - Agent: rolelist/agent/agent.md
        - Core Agent Special:
          - Blackmailed Leader: rolelist/agent/CoreAgentSpecial/BlackmailedLeader.md
          - Runaway Snitch: rolelist/agent/CoreAgentSpecial/RunawaySnitch.md
          - Founder of Agent: rolelist/agent/CoreAgentSpecial/FounderOfAgent.md
        - Core Agent Field Operations:
          - Field Agent: rolelist/agent/CoreAgentFieldOps/FieldAgent.md
          - Determined Deputy: rolelist/agent/CoreAgentFieldOps/DeterminedDeputy.md
          - Drone Operator: rolelist/agent/CoreAgentFieldOps/DroneOperator.md
          - Police Chief: rolelist/agent/CoreAgentFieldOps/PoliceChief.md
          - K-9 Unit: rolelist/agent/CoreAgentFieldOps/K9Unit.md
          - Police Car Driver: rolelist/agent/CoreAgentFieldOps/PoliceCarDriver.md
        - Core Agent Investigative:
          - Forensic Specialist: rolelist/agent/CoreAgentInvest/ForensicSpecialist.md
          - Cybercrime Investigator: rolelist/agent/CoreAgentInvest/CybercrimeInvestigator.md
          - Rookie Informant: rolelist/agent/CoreAgentInvest/RookieInformant.md
          - Helicopter Operator: rolelist/agent/CoreAgentInvest/HelicopterOperator.md
          - Narcotics Officer: rolelist/agent/CoreAgentInvest/NarcoticsOfficer.md
        - Core Agent Offensive:
          - Agent Leader: rolelist/agent/CoreAgentOffensive/AgentLeader.md
          - Cipher Lord: rolelist/agent/CoreAgentOffensive/CipherLord.md
          - Robocop: rolelist/agent/CoreAgentOffensive/Robocop.md
          - Expert Whitehat: rolelist/agent/CoreAgentOffensive/ExpertWhitehat.md
        - Core Agent Utility:
          - Criminal Psychologist: rolelist/agent/CoreAgentUtility/CriminalPsychologist.md
          - Commissary Officer: rolelist/agent/CoreAgentUtility/CommissaryOfficer.md
          - Master Manipulator: rolelist/agent/CoreAgentUtility/MasterManipulator.md
          - Jail Warden: rolelist/agent/CoreAgentUtility/JailWarden.md
          - Animal Tamer: rolelist/agent/CoreAgentUtility/AnimalTamer.md
        - Core Agent Social:
          - District Attorney: rolelist/agent/CoreAgentSocial/DistrictAttorney.md
          - Vigilante Decipherer: rolelist/agent/CoreAgentSocial/VigilanteDecipherer.md
          - Elusive Framer: rolelist/agent/CoreAgentSocial/ElusiveFramer.md
          - Persuaded News Reporter: rolelist/agent/CoreAgentSocial/PersuadedNewsReporter.md
        - Mole Agent Field Operations:
          - Agent Enforcer: rolelist/agent/MoleAgentFieldOps/AgentEnforcer.md
          - Agent CCTV Specialist: rolelist/agent/MoleAgentFieldOps/AgentCCTVSpecialist.md
          - Agent Hardware Hacker: rolelist/agent/MoleAgentFieldOps/AgentHardwareHacker.md
          - Specialist: rolelist/agent/MoleAgentFieldOps/Specialist.md
        - Mole Agent Investigative:
          - Agent Data Scientist: rolelist/agent/MoleAgentInvest/AgentDataScientist.md
          - Agent Social Engineer: rolelist/agent/MoleAgentInvest/AgentSocialEngineer.md
          - Agent Ethical Hacker: rolelist/agent/MoleAgentInvest/AgentEthicalHacker.md
          - Initiator: rolelist/agent/MoleAgentInvest/Initiator.md
        - Mole Agent Offensive:
          - Whitehat: rolelist/agent/MoleAgentOffensive/Whitehat.md
          - Agent Network Specialist: rolelist/agent/MoleAgentOffensive/AgentNetworkSpecialist.md
          - Agent Network Architect: rolelist/agent/MoleAgentOffensive/AgentNetworkArchitect.md
          - Agent Graph Theorist: rolelist/agent/MoleAgentOffensive/AgentGraphTheorist.md
          - Operator: rolelist/agent/MoleAgentOffensive/Operator.md
        - Mole Agent Utility:
          - Agent Company Man: rolelist/agent/MoleAgentUtility/AgentCompanyMan.md
          - Agent Database Manager: rolelist/agent/MoleAgentUtility/AgentDatabaseManager.md
        - Mole Agent Social:
          - Agent Amateur Investigator: rolelist/agent/MoleAgentSocial/AgentAmateurInvestigator.md
          - Agent Technical Recruiter: rolelist/agent/MoleAgentSocial/AgentTechnicalRecruiter.md
      - W3C:
        - W3C: rolelist/w3c/w3c.md
        - W3C Special:
          - W3C Operation Leader: rolelist/w3c/W3CSpecial/W3COperationLeader.md
          - W3C Leader: rolelist/w3c/W3CSpecial/W3CLeader.md
        - W3C Field Operations:
          - W3C Enforcer: rolelist/w3c/W3CFieldOps/W3CEnforcer.md
          - W3C Blackmailer: rolelist/w3c/W3CFieldOps/W3CBlackmailer.md
        - W3C Investigative:
          - W3C Stalker: rolelist/w3c/W3CInvest/W3CStalker.md
          - W3C Forger: rolelist/w3c/W3CInvest/W3CForger.md
          - W3C Ambusher: rolelist/w3c/W3CInvest/W3CAmbusher.md
        - W3C Offensive:
          - W3C Blackhat: rolelist/w3c/W3COffensive/W3CBlackhat.md
          - W3C Disruptor: rolelist/w3c/W3COffensive/W3CDisruptor.md
          - W3C Graph Theorist: rolelist/w3c/W3COffensive/W3CGraphTheorist.md
        - W3C Utility:
          - W3C Lab Technician: rolelist/w3c/W3CUtility/W3CLabTechnician.md
          - W3C Insider: rolelist/w3c/W3CUtility/W3CInsider.md
          - W3C Janitor: rolelist/w3c/W3CUtility/W3CJanitor.md
        - W3C Social:
          - W3C Technical Recruiter: rolelist/w3c/W3CSocial/W3CTechnicalRecruiter.md
          - W3C Assassin: rolelist/w3c/W3CSocial/W3CAssassin.md
      - Paragon:
        - Paragon: rolelist/paragon/paragon.md
        - Paragon Special:
          - Paragon Operation Leader: rolelist/paragon/ParagonSpecial/ParagonOperationLeader.md
          - Paragon Leader: rolelist/paragon/ParagonSpecial/ParagonLeader.md
        - Paragon Field Operations:
          - Paragon Ex-Mercenary: rolelist/paragon/ParagonFieldOps/ParagonExMercenary.md
        - Paragon Investigative:
          - Paragon Journalist: rolelist/paragon/ParagonInvest/ParagonJournalist.md
          - Paragon Informant: rolelist/paragon/ParagonInvest/ParagonInformant.md
          - Paragon Search Engine Optimizer: rolelist/paragon/ParagonInvest/ParagonSearchEngineOptimizer.md
        - Paragon Offensive:
          - Paragon Prodigy: rolelist/paragon/ParagonOffensive/ParagonProdigy.md
        - Paragon Utility:
          - Paragon Security Specialist: rolelist/paragon/ParagonUtility/ParagonSecuritySpecialist.md
          - Paragon Scout: rolelist/paragon/ParagonUtility/ParagonScout.md
        - Paragon Social:
          - Paragon Head of Personnel: rolelist/paragon/ParagonSocial/ParagonHeadOfPersonnel.md
          - Paragon Ex-Mole: rolelist/paragon/ParagonSocial/ParagonExMole.md
          - Paragon Assassin: rolelist/paragon/ParagonSocial/ParagonAssassin.md