site_name: Opsec C
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra_css:
  - stylesheets/styles.css
validation:
  omitted_files: ignore
  absolute_links: ignore
  unrecognized_links: ignore
  not_found: ignore
theme:
  name: material
  font:
    text: Courier New
  palette:
    scheme: custom
    primary: custom
    accent: custom
nav:
    - Home: index.md
    - Opsecs:
        - Opsec C: opsecs/opsecC.md
        - Opsec R: opsecs/opsecR.md
    - General Rules: opsecs/tips.md
    - Role List: opsecs/rolelist.md
    - Roles:
        - Netsec:
            - Netsec:
            - Netsec Special:
            - Netsec Field Operations:
            - Netsec Investigative:
            - Netsec Offensive:
            - Netsec Utility:
            - Netsec Social:
        - Neutral:
            - Neutral:
            - Neutral Special:
            - Neutral Field Operations:
            - Neutral Investigative:
            - Neutral Offensive:
            - Neutral Utility:
            - Neutral Social:
            - Neutral Killing:
        - Agent:
            - Core Agent Special:
            - Core Agent Field Operations:
            - Core Agent Investigative:
            - Core Agent Offensive:
            - Core Agent Utility:
            - Core Agent Social:
            - Mole Agent Field Operations:
            - Mole Agent Investigative:
            - Mole Agent Offensive:
            - Mole Agent Utility:
            - Mole Agent Social:
        - W3C:
            - W3C Special:
            - W3C Field Operations:
            - W3C Investigative:
            - W3C Offensive:
            - W3C Utility:
            - W3C Social:
        - Paragon:
            - Paragon Special:
            - Paragon Field Operations:
            - Paragon Investigative:
            - Paragon Offensive:
            - Paragon Utility:
            - Paragon Social: